#version 450
// Vertex stage for Liquid Glass. Authored in GLSL and transpiled through the
// same glslang -> spirv-cross path as the fragment shader, so the two signatures
// are generated by one toolchain and cannot disagree on register assignment.
layout(location = 0) out vec2 vUV;
layout(location = 1) out vec2 vBackdropUV;
layout(std140, binding = 1) uniform VertexParams {
    vec2 uElementHalfSizePx;
    vec2 _padVS;
};
void main() {
    vec2 p = vec2((gl_VertexIndex & 1) == 1 ? 1.0 : -1.0,
                  (gl_VertexIndex >> 1) == 1 ? 1.0 : -1.0);
    gl_Position = vec4(p, 0.0, 1.0);
    vUV         = p * uElementHalfSizePx;
    // D3D texture origin is top-left, GL bottom-left: flip Y so the fragment
    // maths is identical on both.
    vBackdropUV = vec2(p.x * 0.5 + 0.5, 0.5 - p.y * 0.5);
}
